### ISSUE TITLE
fails with API 5.5

### ISSUE THREAD

**Issue by gfa** [hash-bang/VMM#1]
$ vwm version
Use of my $_ is experimental at /usr/bin/vwm line 954.
Use of my $_ is experimental at /usr/bin/vwm line 958.
vServer name: VMware ESXi 5.5.0 build-1331820
vServer OS: vmnix-x86
API version: 5.5 (build 1331820)
Perl toolkit version: 5.5.0

$ vwm list

SOAP request error - possibly a protocol issue: <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
soapenv:Body
<RetrievePropertiesResponse xmlns="urn:vim25"><returnval><obj type="VirtualMachine">1</obj><propSet><name>availableField</name><val xsi:type="ArrayOfCustomFieldDef"></val></propSet><propSet><name>capability</name><val xsi:type="VirtualMachineCapability"><snapshotOperationsSupported>true</snapshotOperationsSupported><multipleSnapshotsSupported>true</multipleSnapshotsSupported><snapshotConfigSupported>true</snapshotConfigSupported><poweredOffSnapshotsSupported>true</poweredOffSnapshotsSupported><memorySnapshotsSupported>true</memorySnapshotsSupported><revertToSnapshotSupported>true</revertToSnapshotSupported><quiescedSnapshotsSupported>true</quiescedSnapshotsSupported><disableSnapshotsSupported>false</disableSnapshotsSupported><lockSnapshotsSupported>true</lockSnapshotsSupported><consolePreferencesSupported>false</consolePreferencesSupported><cpuFeatureMaskSupported>true</cpuFeatureMaskSupported><s1AcpiManagementSupported>true</s1AcpiManagementSupported><settingScreenResolutionSupported>false</settingScreenResolutionSupported><toolsAutoUpdateSupported>false</toolsAutoUpdateSupported><vmNpivWwnSupported>true</vmNpivWwnSupported><npivWwnOnNonRdmVmSupported>true</npivWwnOnNonRdmVmSupported><vmNpivWwnDisableSupported>true</vmNpivWwnDisableSupported><vmNpivWwnUpdateSupported>true</vmNpivWwnUpdateSupported><swapPlacementSupported>true</swapPlacementSupported><toolsSyncTimeSupported>true</toolsSyncTimeSupported><virtualMmuUsageS
[snip]

i'm using latest debian package, 0.2.0-3

**Comment by gfa** [comment]
sorry, it was an issue on my end, it was an incomplete install of vmware sdk

thanks

**Comment by hash-bang** [comment]
That's good news. I thought it was odd.
