### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by olivierb2** [hash-bang/VMM#2]
Hi,

I'm currently trying to use your software on a Debian Jessie from the official package and it's look like there is an SSL error:

Use of my $_ is experimental at /usr/bin/vwm line 954.
Use of my $_ is experimental at /usr/bin/vwm line 958.
Possible precedence issue with control flow operator at /usr/share/perl/5.20/VMware/VICommon.pm line 2141.
Using config file default profile 'Cluster1'
Server version unavailable at 'https://sgvavmm0001:443/sdk/vimService.wsdl' at /usr/share/perl/5.20/VMware/VICommon.pm line 545.

After looking on Internet, it's look like this is related to an SSL issue, I've tried the magic command provided:

```
 export PERL_LWP_SSL_VERIFY_HOSTNAME=0
```

But, it seems there is no effect. The esxcli and other command provided by Perl SDK are working fine. Any idea?

Thanks

Olivier.

**Comment by hash-bang** [comment]
Odd issue. Most ESX boxes don't have valid certs so I assume this to already be patched.

The VMWare knowledge base does mention an [issue with Windows](http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2033822) if that is the OS you are using.

When I originally wrote the project the API port was usually 8080 though. Is anything actually listening on 443?

**Comment by olivierb2** [comment]
Yes, the server listen on port 443 and meant the connexion is now encrypted.

For information, I managed to fix my certificate issue by installing the certificat (vmware self-signed) in my system, so now I didn't get any warning with wget, unfortunately, this doesn't fix my problem with vmm.

**Comment by hash-bang** [comment]
That's annoying. So even with the above shell variable it still doesn't work?

VMM is a wrapper for the VMWare API so all I can really suggest is heading over to their forums and seeing if anyone has anything similar.

Would love to help but don't have a VMWare ESX box around for testing I'm afraid.
